name: Build and Push Frontend to DockerHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login no DockerHub utilizando variáveis do ambiente
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir e Publicar a Imagem Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-minikube:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/frontend-minikube:latest ${{ env.DOCKER_USERNAME }}/frontend-minikube:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-minikube:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-minikube:${{ github.sha }}
